version: '3'
services:
  tif-llm-1:
    build: .
    volumes:
      - .:/app
    command: /bin/bash -c "python word2vec.py > /app/word2vec_output.txt 2>&1 && python bert.py > /app/bert_output.txt 2>&1"
